# Generated by Django 5.2 on 2025-04-08 18:29

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('pharm', 'PHARM'), ('civil', 'CIVIL'), ('eng', 'ENG'), ('bba', 'BBA'), ('llb', 'LLB'), ('msc', 'M.Sc'), ('mba', 'MBA')], max_length=50)),
                ('semester', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('graduate', 'GRADUATE')], max_length=50)),
                ('batch_no', models.IntegerField()),
                ('phone_no', models.CharField(blank=True, max_length=12, null=True)),
                ('blood_grp', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.CharField(blank=True, max_length=150, null=True)),
                ('relationship_status', models.CharField(blank=True, max_length=20, null=True)),
                ('role', models.CharField(choices=[('student', 'Student'), ('Admin', 'Admin')], default='student', max_length=10)),
                ('profile_photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='profile_photo')),
                ('cover_photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='cover_photo')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
