# Generated by Django 5.2 on 2025-04-14 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_profile_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('graduate', 'GRADUATE')], default='A', max_length=50, null=True),
        ),
    ]
