# Generated by Django 5.2 on 2025-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_points_alter_userprofile_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='section',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=50, null=True),
        ),
    ]
