# Generated by Django 5.2 on 2026-05-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_is_email_verified_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userverification',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
