# Generated by Django 5.2 on 2026-05-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='CINTRACON', max_length=100)),
                ('allow_signup', models.BooleanField(default=True)),
                ('max_file_size_mb', models.IntegerField(default=10)),
                ('allowed_departments', models.JSONField(default=list)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
    ]
