# Generated by Django 5.2 on 2025-04-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopportunities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
