# Generated by Django 5.2 on 2025-10-19 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopportunities', '0002_alter_jobpost_end_time_alter_jobpost_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='deadline',
            field=models.DateField(blank=True, null=True),
        ),
    ]
