# Generated by Django 5.2 on 2025-04-19 09:49

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('note_file', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='note_file')),
                ('drive_link', models.URLField(blank=True, null=True)),
                ('department', models.CharField(choices=[('cse', 'CSE'), ('eee', 'EEE'), ('pharm', 'PHARM'), ('civil', 'CIVIL'), ('eng', 'ENG'), ('bba', 'BBA'), ('llb', 'LLB'), ('msc', 'M.Sc'), ('mba', 'MBA')], max_length=100)),
                ('semester', models.CharField(choices=[('1.1', '1.1'), ('1.2', '1.2'), ('2.1', '2.1'), ('2.2', '2.2'), ('3.1', '3.1'), ('3.2', '3.2'), ('4.1', '4.1'), ('4.2', '4.2'), ('graduate', 'GRADUATE')], max_length=10)),
                ('section', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_sharing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
