# Generated by Django 5.2 on 2025-10-19 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesharing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='total_downloads',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
